### ISSUE TITLE
Drop `is_` prefix in predicate methods?

### ISSUE THREAD

**Issue by derekgottlieb** [exercism/xcrystal#12]
In PR #11, the question was raised whether Crystal had a preference for including prefixes in predicate methods (e.g., `is_pangram?`) or drop them like in Ruby. The coding style section of the Crystal docs is pretty short at this point, so I didn't see any style preference for predicate methods. I did find the following commit from a recent PR that was merged to the core language that would suggest they also prefer to drop the `is_` prefix too:

[Various cleanups #2668](https://github.com/crystal-lang/crystal/pull/2668/commits/f09f1908da8f85a17cec2be812c4f27203b93c85)

Would you like me to go through the existing exercises and drop any prefixes on predicate methods (e.g., `is_leap`)?

**Comment by mhelmetag** [comment]
I'd agree! If it's something that's a best practice in Ruby, it most likely is also in Crystal. By all means change the predicte methods, if you have time!
