### ISSUE TITLE
Generate exercises using x-common

### ISSUE THREAD

**Issue by tejasbubane** [exercism/xcrystal#20]
Looks like this track is about to be launched soon (with almost 9 exercises now). 

I think we should generate all exercises from [x-common](https://github.com/exercism/x-common). I see a lot of PRs in x-ruby changing the static exercise files to dynamically generated ones. Using it from the start in a new repo like this is better instead of converting them later. 

Not sure if this should be enforced on all PRs. What are your views regarding this?

**Comment by elorest** [comment]
I wrote this last night to create a specs from x-common.

```ruby
@cases = [cases, from, x-common]
File.open("spec.cr", "w+") do |f|
  @cases.each do |c|
  f.puts %/it "#{c[:description]}" do/
  f.puts %/  Series.new("#{c[:digits]}").largest_product(#{c[:span]}).should eq #{c[:expected]}/
  f.puts "end"
  end
end
```

**Comment by mhelmetag** [comment]
@elorest , something like this could probably be expanded to make specs for every exercise's json file in the x-common repo.

**Comment by elorest** [comment]
My thoughts as well. I'll work on that when I have a chance. I just put in
2 weeks at my work so I'm swamped  trying to finish up a million things so
I don't leave them in a pinch.

**Comment by tejasbubane** [comment]
Looks like `xruby` also uses some kind of [common generator](https://github.com/exercism/xruby/blob/master/lib/generator.rb). We can follow the same architecture as described in xruby's [generated section](https://github.com/exercism/xruby#generated-test-suites).

**Comment by mhelmetag** [comment]
I feel like the test metadata (json files) in `x-common` need to be standardized with description, input and expected. Currently there are some files that are kind of all over the place... but I am making some progress with a generator that pulls directly from the github repo online.

**Comment by kytrinyx** [comment]
Yeah, we haven't really figured out what to standardize on, and any thoughts about how to do that are very welcome.  If you have thoughts about it, would you mind opening something in the x-common repository?

> I am making some progress with a generator that pulls directly from the github repo online.

Sweet! There's some talk about improving the Ruby generators, too. https://github.com/exercism/xruby/issues/396#issuecomment-234739123 If several people are thinking about this at once, it could be worth starting a discussion in the github.com/exercism/discussions/issues repo.

**Comment by mhelmetag** [comment]
@bmulvihill has ported over a spec generator similar to the one in xruby 🎊 so now we can make test case templates like they do! One thing I will work on adding is getting the json from x-common over http or locally (so that there's a choice).
