### ISSUE TITLE
crystal tool format

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcrystal#30]
I noticed in the email notifications on PR #22 that @asterite said: _I would suggest running `crystal tool format` on the whole project to automatically make the code follow the recommended style._

First of all: I _love_ it when languages have a tool to autoformat for the recommended style. (Thank you for that!)

Second: we should recommend this in the docs for the language track.

Third: We could implement a service like for Go (`gofmt`) where we check if their submission matches the output from the tool and if it doesn't add a friendly comment from rikki about the tool and the value of consistency etc.

The go stuff is implemented directly in rikki- (because I'm lazy), but if it's simple enough to spin up a small API somewhere with crystal installed on the command-line, rikki- could ask the service and report back, like it does in Ruby. https://github.com/exercism/rikki/tree/master/analysis

**Comment by mhelmetag** [comment]
So after adding a note about using the built-in formatter in the docs, it looks like there's one more item here: to implement a basic format checker for rikki.

**Comment by kytrinyx** [comment]
Yes! The easiest way to do that is probably to spin up a tiny API on heroku, and then have rikki- do the same thing as with the ruby stuff: receive a job that contains the submission uuid, ask the exercism API for the code, and then submit the code to the formatting checker API.

**Comment by mhelmetag** [comment]
Got a little Crystal API doing format checking https://github.com/mhelmetag/exercism_cfs. Hopefully I can get a PR to rikki soon :D

**Comment by mhelmetag** [comment]
rikki knows a little bit about Crystal now!!!
