### ISSUE TITLE
largest-series-product: Should it raise on invalid inputs?

### ISSUE THREAD

**Issue by petertseng** [exercism/xcrystal#38]
Currently, the [largest-series-product tests](https://github.com/exercism/xcrystal/blob/master/exercises/largest-series-product/largest_series_product_spec.cr) expect a value of -1 if the input is invalid in some way (non-digit in digit sequence, negative window size, too-large window size). Should it raise an exception instead? Not sure what the idiomatic way is in Crystal to test for errors, whether it is normal to expect impossible values, but it seems if exceptions are available they can be used.

**Comment by asterite** [comment]
Yes, I was also surprised to see this. I think raising `ArgumentError` is fine here. Returning `nil` is also fine, but then requires you to explicitly handle the return value.

**Comment by petertseng** [comment]
OK, given that it seems reasonable behavior, I intend to submit a PR.
