### ISSUE TITLE
rna-transcription: don't transcribe both ways

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xcrystal#5]
I can't remember the history of this, but we ended up with a weird non-biological thing in the RNA transcription exercise, where some test suites also have tests for transcribing from RNA back to DNA. This makes no sense.

If this track does have tests for the reverse transcription, we should remove them, and also simplify the reference solution to match.

If this track doesn't have any tests for RNA->DNA transcription, then this issue can be closed.

See https://github.com/exercism/x-common/issues/148

**Comment by mhelmetag** [comment]
:D I fixed this issue for ruby and js so I remembered. Currently I only transcribe DNA -> RNA so I think that's okay. I basically copied my test cases from ruby and crystalized them.
