### ISSUE TITLE
[hamming] Levenshtein is not the same as Hamming distance

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcrystal#8]
Levenshtein-distance is not the same as Hamming-distance.

From Wikipedia, I have the following snippet of ruby code which does calculate the Hamming-Distance:

```rb
def hammingDistance(s1, s2)
    raise "ERROR: Hamming: Non equal lengths" if s1.length != s2.length
    (s1.chars.zip(s2.chars)).count {|l, r| l != r}
end
```

Translating this to crystal yields the following:

```cr
module Hamming
  def self.compute(l, r)
    raise(ArgumentError.new()) if l.size != r.size
    l.chars.zip(r.chars).count { |x| x[0] != x[1] }
  end
end
```

But running the test yields a fail:

```plain
Failures:

  1) Hamming #compute computes a distance for large strands
     Failure/Error: Hamming.compute("GGACGGATTCTG", "AGGACGGATTCT").should eq 2

       expected: 2
            got: 9
```

Counting this by hand, I do get a distance of 9, like my code.

Also looking at the site of Levenshtein distance on Wikipedia, it seems that L-distance is comparing everything with everything.

According to my observations the difference is especially visible when having rotatet sequences. H-distance of `"abcdefgh"` and `"bcdefgha"` is 8, since there is not a single character as the one on the same index on the other string, while the L-distance of both is 2!

**Comment by mhelmetag** [comment]
Yep! Totally correct. Got excited, used Crystal's built-in Levenshtein even though it's not what I wanted, and glossed over the details.
